// source: larp/events.proto
// noinspection ES6ConvertVarToLetConst

/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.larp.Event', null, global);
goog.exportSymbol('proto.larp.EventAttendance', null, global);
goog.exportSymbol('proto.larp.EventAttendanceType', null, global);
goog.exportSymbol('proto.larp.EventComponent', null, global);
goog.exportSymbol('proto.larp.EventComponentAttendance', null, global);
goog.exportSymbol('proto.larp.EventRsvp', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.larp.EventComponent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.larp.EventComponent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.larp.EventComponent.displayName = 'proto.larp.EventComponent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.larp.EventComponentAttendance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.larp.EventComponentAttendance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.larp.EventComponentAttendance.displayName = 'proto.larp.EventComponentAttendance';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.larp.EventAttendance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.larp.EventAttendance.repeatedFields_, null);
};
goog.inherits(proto.larp.EventAttendance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.larp.EventAttendance.displayName = 'proto.larp.EventAttendance';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.larp.Event = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.larp.Event.repeatedFields_, null);
};
goog.inherits(proto.larp.Event, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.larp.Event.displayName = 'proto.larp.Event';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.larp.EventComponent.prototype.toObject = function(opt_includeInstance) {
  return proto.larp.EventComponent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.larp.EventComponent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.EventComponent.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    date: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.larp.EventComponent}
 */
proto.larp.EventComponent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.larp.EventComponent;
  return proto.larp.EventComponent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.larp.EventComponent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.larp.EventComponent}
 */
proto.larp.EventComponent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.larp.EventComponent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.larp.EventComponent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.larp.EventComponent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.EventComponent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.larp.EventComponent.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.EventComponent} returns this
 */
proto.larp.EventComponent.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string date = 2;
 * @return {string}
 */
proto.larp.EventComponent.prototype.getDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.EventComponent} returns this
 */
proto.larp.EventComponent.prototype.setDate = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.larp.EventComponentAttendance.prototype.toObject = function(opt_includeInstance) {
  return proto.larp.EventComponentAttendance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.larp.EventComponentAttendance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.EventComponentAttendance.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    characterId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    characterName: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.larp.EventComponentAttendance}
 */
proto.larp.EventComponentAttendance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.larp.EventComponentAttendance;
  return proto.larp.EventComponentAttendance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.larp.EventComponentAttendance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.larp.EventComponentAttendance}
 */
proto.larp.EventComponentAttendance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.larp.EventAttendanceType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCharacterId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCharacterName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.larp.EventComponentAttendance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.larp.EventComponentAttendance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.larp.EventComponentAttendance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.EventComponentAttendance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional EventAttendanceType type = 1;
 * @return {!proto.larp.EventAttendanceType}
 */
proto.larp.EventComponentAttendance.prototype.getType = function() {
  return /** @type {!proto.larp.EventAttendanceType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.larp.EventAttendanceType} value
 * @return {!proto.larp.EventComponentAttendance} returns this
 */
proto.larp.EventComponentAttendance.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string character_id = 2;
 * @return {string}
 */
proto.larp.EventComponentAttendance.prototype.getCharacterId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.EventComponentAttendance} returns this
 */
proto.larp.EventComponentAttendance.prototype.setCharacterId = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.larp.EventComponentAttendance} returns this
 */
proto.larp.EventComponentAttendance.prototype.clearCharacterId = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.larp.EventComponentAttendance.prototype.hasCharacterId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string character_name = 3;
 * @return {string}
 */
proto.larp.EventComponentAttendance.prototype.getCharacterName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.EventComponentAttendance} returns this
 */
proto.larp.EventComponentAttendance.prototype.setCharacterName = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.larp.EventComponentAttendance} returns this
 */
proto.larp.EventComponentAttendance.prototype.clearCharacterName = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.larp.EventComponentAttendance.prototype.hasCharacterName = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.larp.EventAttendance.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.larp.EventAttendance.prototype.toObject = function(opt_includeInstance) {
  return proto.larp.EventAttendance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.larp.EventAttendance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.EventAttendance.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    accountName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    moonstone: jspb.Message.getFieldWithDefault(msg, 5, 0),
    rsvp: jspb.Message.getFieldWithDefault(msg, 6, 0),
    componentsList: jspb.Message.toObjectList(msg.getComponentsList(),
    proto.larp.EventComponentAttendance.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.larp.EventAttendance}
 */
proto.larp.EventAttendance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.larp.EventAttendance;
  return proto.larp.EventAttendance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.larp.EventAttendance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.larp.EventAttendance}
 */
proto.larp.EventAttendance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountName(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMoonstone(value);
      break;
    case 6:
      var value = /** @type {!proto.larp.EventRsvp} */ (reader.readEnum());
      msg.setRsvp(value);
      break;
    case 7:
      var value = new proto.larp.EventComponentAttendance;
      reader.readMessage(value,proto.larp.EventComponentAttendance.deserializeBinaryFromReader);
      msg.addComponents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.larp.EventAttendance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.larp.EventAttendance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.larp.EventAttendance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.EventAttendance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAccountName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMoonstone();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getRsvp();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getComponentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.larp.EventComponentAttendance.serializeBinaryToWriter
    );
  }
};


/**
 * optional string account_id = 1;
 * @return {string}
 */
proto.larp.EventAttendance.prototype.getAccountId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.EventAttendance} returns this
 */
proto.larp.EventAttendance.prototype.setAccountId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string account_name = 2;
 * @return {string}
 */
proto.larp.EventAttendance.prototype.getAccountName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.EventAttendance} returns this
 */
proto.larp.EventAttendance.prototype.setAccountName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 moonstone = 5;
 * @return {number}
 */
proto.larp.EventAttendance.prototype.getMoonstone = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.larp.EventAttendance} returns this
 */
proto.larp.EventAttendance.prototype.setMoonstone = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional EventRsvp rsvp = 6;
 * @return {!proto.larp.EventRsvp}
 */
proto.larp.EventAttendance.prototype.getRsvp = function() {
  return /** @type {!proto.larp.EventRsvp} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.larp.EventRsvp} value
 * @return {!proto.larp.EventAttendance} returns this
 */
proto.larp.EventAttendance.prototype.setRsvp = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * repeated EventComponentAttendance components = 7;
 * @return {!Array<!proto.larp.EventComponentAttendance>}
 */
proto.larp.EventAttendance.prototype.getComponentsList = function() {
  return /** @type{!Array<!proto.larp.EventComponentAttendance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.larp.EventComponentAttendance, 7));
};


/**
 * @param {!Array<!proto.larp.EventComponentAttendance>} value
 * @return {!proto.larp.EventAttendance} returns this
*/
proto.larp.EventAttendance.prototype.setComponentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.larp.EventComponentAttendance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.EventComponentAttendance}
 */
proto.larp.EventAttendance.prototype.addComponents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.larp.EventComponentAttendance, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.EventAttendance} returns this
 */
proto.larp.EventAttendance.prototype.clearComponentsList = function() {
  return this.setComponentsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.larp.Event.repeatedFields_ = [9,10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.larp.Event.prototype.toObject = function(opt_includeInstance) {
  return proto.larp.Event.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.larp.Event} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.Event.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    gameId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    title: jspb.Message.getFieldWithDefault(msg, 3, ""),
    location: jspb.Message.getFieldWithDefault(msg, 4, ""),
    date: jspb.Message.getFieldWithDefault(msg, 5, ""),
    eventType: jspb.Message.getFieldWithDefault(msg, 6, ""),
    rsvp: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    hidden: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    componentsList: jspb.Message.toObjectList(msg.getComponentsList(),
    proto.larp.EventComponent.toObject, includeInstance),
    attendeesList: jspb.Message.toObjectList(msg.getAttendeesList(),
    proto.larp.EventAttendance.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.larp.Event}
 */
proto.larp.Event.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.larp.Event;
  return proto.larp.Event.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.larp.Event} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.larp.Event}
 */
proto.larp.Event.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGameId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDate(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventType(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRsvp(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHidden(value);
      break;
    case 9:
      var value = new proto.larp.EventComponent;
      reader.readMessage(value,proto.larp.EventComponent.deserializeBinaryFromReader);
      msg.addComponents(value);
      break;
    case 10:
      var value = new proto.larp.EventAttendance;
      reader.readMessage(value,proto.larp.EventAttendance.deserializeBinaryFromReader);
      msg.addAttendees(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.larp.Event.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.larp.Event.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.larp.Event} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.Event.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGameId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDate();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getEventType();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRsvp();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getHidden();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getComponentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.larp.EventComponent.serializeBinaryToWriter
    );
  }
  f = message.getAttendeesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.larp.EventAttendance.serializeBinaryToWriter
    );
  }
};


/**
 * optional string event_id = 1;
 * @return {string}
 */
proto.larp.Event.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.setEventId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string game_id = 2;
 * @return {string}
 */
proto.larp.Event.prototype.getGameId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.setGameId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.larp.Event.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string location = 4;
 * @return {string}
 */
proto.larp.Event.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.setLocation = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string date = 5;
 * @return {string}
 */
proto.larp.Event.prototype.getDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.setDate = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string event_type = 6;
 * @return {string}
 */
proto.larp.Event.prototype.getEventType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.setEventType = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bool rsvp = 7;
 * @return {boolean}
 */
proto.larp.Event.prototype.getRsvp = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.setRsvp = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool hidden = 8;
 * @return {boolean}
 */
proto.larp.Event.prototype.getHidden = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.setHidden = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * repeated EventComponent components = 9;
 * @return {!Array<!proto.larp.EventComponent>}
 */
proto.larp.Event.prototype.getComponentsList = function() {
  return /** @type{!Array<!proto.larp.EventComponent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.larp.EventComponent, 9));
};


/**
 * @param {!Array<!proto.larp.EventComponent>} value
 * @return {!proto.larp.Event} returns this
*/
proto.larp.Event.prototype.setComponentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.larp.EventComponent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.EventComponent}
 */
proto.larp.Event.prototype.addComponents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.larp.EventComponent, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.clearComponentsList = function() {
  return this.setComponentsList([]);
};


/**
 * repeated EventAttendance attendees = 10;
 * @return {!Array<!proto.larp.EventAttendance>}
 */
proto.larp.Event.prototype.getAttendeesList = function() {
  return /** @type{!Array<!proto.larp.EventAttendance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.larp.EventAttendance, 10));
};


/**
 * @param {!Array<!proto.larp.EventAttendance>} value
 * @return {!proto.larp.Event} returns this
*/
proto.larp.Event.prototype.setAttendeesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.larp.EventAttendance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.EventAttendance}
 */
proto.larp.Event.prototype.addAttendees = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.larp.EventAttendance, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.Event} returns this
 */
proto.larp.Event.prototype.clearAttendeesList = function() {
  return this.setAttendeesList([]);
};


/**
 * @enum {number}
 */
proto.larp.EventRsvp = {
  EVENT_RSVP_UNANSWERED: 0,
  EVENT_RSVP_NO: 1,
  EVENT_RSVP_MAYBE: 2,
  EVENT_RSVP_YES: 3,
  EVENT_RSVP_CONFIRMED: 4,
  EVENT_RSVP_APPROVED: 5
};

/**
 * @enum {number}
 */
proto.larp.EventAttendanceType = {
  EVENT_ATTENDANCE_TYPE_PLAYER: 0,
  EVENT_ATTENDANCE_TYPE_STAFF: 1,
  EVENT_ATTENDANCE_TYPE_MIXED: 2
};

goog.object.extend(exports, proto.larp);
