// source: larp/mw5e/fifthedition.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var larp_mw5e_character_pb = require('../../larp/mw5e/character_pb.js');
goog.object.extend(proto, larp_mw5e_character_pb);
var larp_mw5e_gifts_pb = require('../../larp/mw5e/gifts_pb.js');
goog.object.extend(proto, larp_mw5e_gifts_pb);
var larp_mw5e_occupations_pb = require('../../larp/mw5e/occupations_pb.js');
goog.object.extend(proto, larp_mw5e_occupations_pb);
var larp_mw5e_other_pb = require('../../larp/mw5e/other_pb.js');
goog.object.extend(proto, larp_mw5e_other_pb);
var larp_mw5e_skills_pb = require('../../larp/mw5e/skills_pb.js');
goog.object.extend(proto, larp_mw5e_skills_pb);
goog.exportSymbol('proto.larp.mw5e.GameState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.larp.mw5e.GameState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.larp.mw5e.GameState.repeatedFields_, null);
};
goog.inherits(proto.larp.mw5e.GameState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.larp.mw5e.GameState.displayName = 'proto.larp.mw5e.GameState';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.larp.mw5e.GameState.repeatedFields_ = [10,11,12,13,14,15,16,17];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.larp.mw5e.GameState.prototype.toObject = function(opt_includeInstance) {
  return proto.larp.mw5e.GameState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.larp.mw5e.GameState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.mw5e.GameState.toObject = function(includeInstance, msg) {
  var f, obj = {
    lastUpdated: jspb.Message.getFieldWithDefault(msg, 1, ""),
    revision: jspb.Message.getFieldWithDefault(msg, 2, ""),
    giftsList: jspb.Message.toObjectList(msg.getGiftsList(),
    larp_mw5e_gifts_pb.Gift.toObject, includeInstance),
    skillsList: jspb.Message.toObjectList(msg.getSkillsList(),
    larp_mw5e_skills_pb.SkillDefinition.toObject, includeInstance),
    occupationsList: jspb.Message.toObjectList(msg.getOccupationsList(),
    larp_mw5e_occupations_pb.Occupation.toObject, includeInstance),
    advantagesList: jspb.Message.toObjectList(msg.getAdvantagesList(),
    larp_mw5e_other_pb.Vantage.toObject, includeInstance),
    disadvantagesList: jspb.Message.toObjectList(msg.getDisadvantagesList(),
    larp_mw5e_other_pb.Vantage.toObject, includeInstance),
    religionsList: jspb.Message.toObjectList(msg.getReligionsList(),
    larp_mw5e_other_pb.Religion.toObject, includeInstance),
    homeChaptersList: jspb.Message.toObjectList(msg.getHomeChaptersList(),
    larp_mw5e_other_pb.HomeChapter.toObject, includeInstance),
    spellsList: jspb.Message.toObjectList(msg.getSpellsList(),
    larp_mw5e_other_pb.Spell.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.larp.mw5e.GameState}
 */
proto.larp.mw5e.GameState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.larp.mw5e.GameState;
  return proto.larp.mw5e.GameState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.larp.mw5e.GameState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.larp.mw5e.GameState}
 */
proto.larp.mw5e.GameState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastUpdated(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRevision(value);
      break;
    case 10:
      var value = new larp_mw5e_gifts_pb.Gift;
      reader.readMessage(value,larp_mw5e_gifts_pb.Gift.deserializeBinaryFromReader);
      msg.addGifts(value);
      break;
    case 11:
      var value = new larp_mw5e_skills_pb.SkillDefinition;
      reader.readMessage(value,larp_mw5e_skills_pb.SkillDefinition.deserializeBinaryFromReader);
      msg.addSkills(value);
      break;
    case 12:
      var value = new larp_mw5e_occupations_pb.Occupation;
      reader.readMessage(value,larp_mw5e_occupations_pb.Occupation.deserializeBinaryFromReader);
      msg.addOccupations(value);
      break;
    case 13:
      var value = new larp_mw5e_other_pb.Vantage;
      reader.readMessage(value,larp_mw5e_other_pb.Vantage.deserializeBinaryFromReader);
      msg.addAdvantages(value);
      break;
    case 14:
      var value = new larp_mw5e_other_pb.Vantage;
      reader.readMessage(value,larp_mw5e_other_pb.Vantage.deserializeBinaryFromReader);
      msg.addDisadvantages(value);
      break;
    case 15:
      var value = new larp_mw5e_other_pb.Religion;
      reader.readMessage(value,larp_mw5e_other_pb.Religion.deserializeBinaryFromReader);
      msg.addReligions(value);
      break;
    case 16:
      var value = new larp_mw5e_other_pb.HomeChapter;
      reader.readMessage(value,larp_mw5e_other_pb.HomeChapter.deserializeBinaryFromReader);
      msg.addHomeChapters(value);
      break;
    case 17:
      var value = new larp_mw5e_other_pb.Spell;
      reader.readMessage(value,larp_mw5e_other_pb.Spell.deserializeBinaryFromReader);
      msg.addSpells(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.larp.mw5e.GameState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.larp.mw5e.GameState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.larp.mw5e.GameState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.larp.mw5e.GameState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLastUpdated();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRevision();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGiftsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      larp_mw5e_gifts_pb.Gift.serializeBinaryToWriter
    );
  }
  f = message.getSkillsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      larp_mw5e_skills_pb.SkillDefinition.serializeBinaryToWriter
    );
  }
  f = message.getOccupationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      larp_mw5e_occupations_pb.Occupation.serializeBinaryToWriter
    );
  }
  f = message.getAdvantagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      larp_mw5e_other_pb.Vantage.serializeBinaryToWriter
    );
  }
  f = message.getDisadvantagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      larp_mw5e_other_pb.Vantage.serializeBinaryToWriter
    );
  }
  f = message.getReligionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      larp_mw5e_other_pb.Religion.serializeBinaryToWriter
    );
  }
  f = message.getHomeChaptersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      16,
      f,
      larp_mw5e_other_pb.HomeChapter.serializeBinaryToWriter
    );
  }
  f = message.getSpellsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      17,
      f,
      larp_mw5e_other_pb.Spell.serializeBinaryToWriter
    );
  }
};


/**
 * optional string last_updated = 1;
 * @return {string}
 */
proto.larp.mw5e.GameState.prototype.getLastUpdated = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.setLastUpdated = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string revision = 2;
 * @return {string}
 */
proto.larp.mw5e.GameState.prototype.getRevision = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.setRevision = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Gift gifts = 10;
 * @return {!Array<!proto.larp.mw5e.Gift>}
 */
proto.larp.mw5e.GameState.prototype.getGiftsList = function() {
  return /** @type{!Array<!proto.larp.mw5e.Gift>} */ (
    jspb.Message.getRepeatedWrapperField(this, larp_mw5e_gifts_pb.Gift, 10));
};


/**
 * @param {!Array<!proto.larp.mw5e.Gift>} value
 * @return {!proto.larp.mw5e.GameState} returns this
*/
proto.larp.mw5e.GameState.prototype.setGiftsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.larp.mw5e.Gift=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.mw5e.Gift}
 */
proto.larp.mw5e.GameState.prototype.addGifts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.larp.mw5e.Gift, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.clearGiftsList = function() {
  return this.setGiftsList([]);
};


/**
 * repeated SkillDefinition skills = 11;
 * @return {!Array<!proto.larp.mw5e.SkillDefinition>}
 */
proto.larp.mw5e.GameState.prototype.getSkillsList = function() {
  return /** @type{!Array<!proto.larp.mw5e.SkillDefinition>} */ (
    jspb.Message.getRepeatedWrapperField(this, larp_mw5e_skills_pb.SkillDefinition, 11));
};


/**
 * @param {!Array<!proto.larp.mw5e.SkillDefinition>} value
 * @return {!proto.larp.mw5e.GameState} returns this
*/
proto.larp.mw5e.GameState.prototype.setSkillsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.larp.mw5e.SkillDefinition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.mw5e.SkillDefinition}
 */
proto.larp.mw5e.GameState.prototype.addSkills = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.larp.mw5e.SkillDefinition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.clearSkillsList = function() {
  return this.setSkillsList([]);
};


/**
 * repeated Occupation occupations = 12;
 * @return {!Array<!proto.larp.mw5e.Occupation>}
 */
proto.larp.mw5e.GameState.prototype.getOccupationsList = function() {
  return /** @type{!Array<!proto.larp.mw5e.Occupation>} */ (
    jspb.Message.getRepeatedWrapperField(this, larp_mw5e_occupations_pb.Occupation, 12));
};


/**
 * @param {!Array<!proto.larp.mw5e.Occupation>} value
 * @return {!proto.larp.mw5e.GameState} returns this
*/
proto.larp.mw5e.GameState.prototype.setOccupationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.larp.mw5e.Occupation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.mw5e.Occupation}
 */
proto.larp.mw5e.GameState.prototype.addOccupations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.larp.mw5e.Occupation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.clearOccupationsList = function() {
  return this.setOccupationsList([]);
};


/**
 * repeated Vantage advantages = 13;
 * @return {!Array<!proto.larp.mw5e.Vantage>}
 */
proto.larp.mw5e.GameState.prototype.getAdvantagesList = function() {
  return /** @type{!Array<!proto.larp.mw5e.Vantage>} */ (
    jspb.Message.getRepeatedWrapperField(this, larp_mw5e_other_pb.Vantage, 13));
};


/**
 * @param {!Array<!proto.larp.mw5e.Vantage>} value
 * @return {!proto.larp.mw5e.GameState} returns this
*/
proto.larp.mw5e.GameState.prototype.setAdvantagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.larp.mw5e.Vantage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.mw5e.Vantage}
 */
proto.larp.mw5e.GameState.prototype.addAdvantages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.larp.mw5e.Vantage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.clearAdvantagesList = function() {
  return this.setAdvantagesList([]);
};


/**
 * repeated Vantage disadvantages = 14;
 * @return {!Array<!proto.larp.mw5e.Vantage>}
 */
proto.larp.mw5e.GameState.prototype.getDisadvantagesList = function() {
  return /** @type{!Array<!proto.larp.mw5e.Vantage>} */ (
    jspb.Message.getRepeatedWrapperField(this, larp_mw5e_other_pb.Vantage, 14));
};


/**
 * @param {!Array<!proto.larp.mw5e.Vantage>} value
 * @return {!proto.larp.mw5e.GameState} returns this
*/
proto.larp.mw5e.GameState.prototype.setDisadvantagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.larp.mw5e.Vantage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.mw5e.Vantage}
 */
proto.larp.mw5e.GameState.prototype.addDisadvantages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.larp.mw5e.Vantage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.clearDisadvantagesList = function() {
  return this.setDisadvantagesList([]);
};


/**
 * repeated Religion religions = 15;
 * @return {!Array<!proto.larp.mw5e.Religion>}
 */
proto.larp.mw5e.GameState.prototype.getReligionsList = function() {
  return /** @type{!Array<!proto.larp.mw5e.Religion>} */ (
    jspb.Message.getRepeatedWrapperField(this, larp_mw5e_other_pb.Religion, 15));
};


/**
 * @param {!Array<!proto.larp.mw5e.Religion>} value
 * @return {!proto.larp.mw5e.GameState} returns this
*/
proto.larp.mw5e.GameState.prototype.setReligionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.larp.mw5e.Religion=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.mw5e.Religion}
 */
proto.larp.mw5e.GameState.prototype.addReligions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.larp.mw5e.Religion, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.clearReligionsList = function() {
  return this.setReligionsList([]);
};


/**
 * repeated HomeChapter home_chapters = 16;
 * @return {!Array<!proto.larp.mw5e.HomeChapter>}
 */
proto.larp.mw5e.GameState.prototype.getHomeChaptersList = function() {
  return /** @type{!Array<!proto.larp.mw5e.HomeChapter>} */ (
    jspb.Message.getRepeatedWrapperField(this, larp_mw5e_other_pb.HomeChapter, 16));
};


/**
 * @param {!Array<!proto.larp.mw5e.HomeChapter>} value
 * @return {!proto.larp.mw5e.GameState} returns this
*/
proto.larp.mw5e.GameState.prototype.setHomeChaptersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 16, value);
};


/**
 * @param {!proto.larp.mw5e.HomeChapter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.mw5e.HomeChapter}
 */
proto.larp.mw5e.GameState.prototype.addHomeChapters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 16, opt_value, proto.larp.mw5e.HomeChapter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.clearHomeChaptersList = function() {
  return this.setHomeChaptersList([]);
};


/**
 * repeated Spell spells = 17;
 * @return {!Array<!proto.larp.mw5e.Spell>}
 */
proto.larp.mw5e.GameState.prototype.getSpellsList = function() {
  return /** @type{!Array<!proto.larp.mw5e.Spell>} */ (
    jspb.Message.getRepeatedWrapperField(this, larp_mw5e_other_pb.Spell, 17));
};


/**
 * @param {!Array<!proto.larp.mw5e.Spell>} value
 * @return {!proto.larp.mw5e.GameState} returns this
*/
proto.larp.mw5e.GameState.prototype.setSpellsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 17, value);
};


/**
 * @param {!proto.larp.mw5e.Spell=} opt_value
 * @param {number=} opt_index
 * @return {!proto.larp.mw5e.Spell}
 */
proto.larp.mw5e.GameState.prototype.addSpells = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 17, opt_value, proto.larp.mw5e.Spell, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.larp.mw5e.GameState} returns this
 */
proto.larp.mw5e.GameState.prototype.clearSpellsList = function() {
  return this.setSpellsList([]);
};


goog.object.extend(exports, proto.larp.mw5e);
