name: Build and Push via Docker

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login ${{ vars.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} && \
        docker build . --file Dockerfile \
            --tag ${{ vars.REGISTRY_URL }}/larpdev:${{ github.run_number }} \
            --tag ${{ vars.REGISTRY_URL }}/larpdev:latest \
            --build-arg BUILD_REVISION=${{ github.run_number }} && \
        docker image push ${{ vars.REGISTRY_URL }}/larpdev:${{ github.run_number }} && \
        docker image push ${{ vars.REGISTRY_URL }}/larpdev:latest
